[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.0"
either = "1.13.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

rayon = "1.10.0"